language: android

before_install:
    - 'sudo mv /usr/local/android-sdk/tools/android-* /usr/local/bin'
    - "android-update-sdk --components='platform-tools,tools' --accept-licenses='.+'"
    - "android-update-sdk --components='build-tools-20.0.0' --accept-licenses='.+'"
    - "android-update-sdk --components='android-20' --accept-licenses='.+'"

script:
  ./gradlew build
